[[SpringBoot]]
=== *Spring Boot* auto-configuration

The Holon platform provides https://projects.spring.io/spring-boot[Spring Boot^] *auto-configuration* features for the most of the platform modules, including the _core_ module.

To enable the core Spring Boot auto-configuration capabilities, the following artifact must be included in your project dependencies:

[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-spring-boot</artifactId>
<version>{revnumber}</version>
----

See below for the available auto-configuration features.

==== Spring context scope auto-configuration

The <<SpringContextScope,Spring context scope>> is automatically enabled.

This has the same effect as using the `@EnableBeanContext` annotation on Spring configuration classes, with the `lookupByType()` attribute set as true by default.

The `holon.context.bean-lookup-by-type` configuration property name can be used to configure the _resource lookup strategy_, enabling or not the _lookup by type_ mode.

TIP: See the <<SpringContextScope>> documentation section for details.

To disable this auto-configuration feature, the link:{apidir}/com/holonplatform/spring/boot/EnableBeanContextAutoConfiguration.html[EnableBeanContextAutoConfiguration^] class can be excluded from the Spring Boot auto-configuration classes:

[source, java]
----
@EnableAutoConfiguration(exclude={EnableBeanContextAutoConfiguration.class})
----

==== Spring _tenant_ scope auto-configuration

If a link:{apidir}/com/holonplatform/core/tenancy/TenantResolver.html[TenantResolver^] type bean is available in Spring application context and a _single candidate_ can be determined, the <<SpringTenantScope>> is automatically registered and enabled.

This has the same effect as using the `@EnableTenantScope` annotation on Spring configuration classes.

TIP: See the <<SpringTenantScope>> documentation section for details about the _tenant_ scope.

To disable this auto-configuration feature, the link:{apidir}/com/holonplatform/spring/boot/TenantScopeAutoConfiguration.html[TenantScopeAutoConfiguration^] class  can be excluded from the Spring Boot auto-configuration classes:

[source, java]
----
@EnableAutoConfiguration(exclude={TenantScopeAutoConfiguration.class})
----

[[Starters]]
==== Spring Boot starters

The following Spring Boot _starter_ artifact is available to provide a quick project configuration setup using Maven dependency system:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-starter</artifactId>
<version>{revnumber}</version>
----

The starter provides the dependency to the `holon-spring-boot` artifact, enabling the auto-configuration features listed above, in addition to the default *core* Spring Boot starter (`spring-boot-starter`), which provides auto-configuration support, logging and YAML support.

See the link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter[Spring Boot starters documentation^] for details about the Spring Boot _starters_ topic and the core Spring Boot starter features.
