[[Credentials]]
=== Credentials

The platform provides a support for authentication _credentials_ management, relying on the following structures:

* The `Credentials` interface to represent credentials data, i.e. the *secret* and the encoding informations related to it
* The `CredentialsContainer` interface identifies an object which provides credentials data (for example, the stored account informations related to a principal and the credentials provided by a _principal_ during and authentication process)
* The `CredentialsMatcher` deals with credentials checking, and it is able to determine if two credentials data structures match (for example, if provided credentials match the account stored credentials)

==== Create and encode Credentials

The link:{apidir}/com/holonplatform/auth/Credentials.html[Credentials^] interface provides a _builder_ to create and encode a `Credentials` representation.

The `Credentials` builder provides method to encode a *secret* by using a _hashing_ algorithm (specifying also a _salt_ and the hash iterations to be performed), specifing an optional _expiry date_ and encode the secret using, for example, `Base64`.

[source, java]
.Credentials build examples
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=credentials,indent=0]
----
<1> Simple credentials using `test` as secret and no encodings
<2> Credentials using `test` as secret and `MD5` as hashing algorithm
<3> Credentials using `test` as secret and `MD5` as hashing algorithm, with a _salt_ and 7 hashing iterations
<4> Credentials using `test` as secret and `MD5` as hashing algorithm, encoded using _Base64_
<5> Simple credentials using `test` as secret and no encodings, specifying an _expiry date_

==== Credentials encoder

To encode credentials data, for example for storing purposes, the `Credentials` interface provides an `Encoder` interface, which can be obtained using the `encoder()` static method.

[source, java]
.Credentials encoding examples
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=encoder,indent=0]
----
<1> Credentials using `test` as secret and _Base64_ encoded
<2> Credentials using `test` as secret and `SHA-256` as hashing algorithm, returned as bytes
<3> Credentials using `test` as secret and `SHA-256` as hashing algorithm, with a _salt_ and _Base64_ encoded
<4> Credentials using `test` as secret and `SHA-512` as hashing algorithm, encoded using _Base64_ with the UTF-8 charset

==== Credentials matching

Credentials matching can be performed using a link:{apidir}/com/holonplatform/auth/CredentialsContainer.CredentialsMatcher.html[CredentialsMatcher^].

The platform provides a *default* `CredentialsMatcher` implementation which can be obtained using the `defaultMatcher()` method on the `CredentialsContainer` interface.

The default credentials matcher tries to employ best-practices and common behaviours to perform credentials validation and matching:

* Try to convert generic Object credentials data into a *byte array*:
** It supports `char[]`, `String`, `File` and `InputStream` for direct bytes conversion
** It supports `Credentials` type, using the `getSecret()` method to obtain the bytes
* If the provided credentials data are of `Credentials` type and an _expiry date_ is provided, it checks the credentials are not expired
* It check if the array of bytes obtained from the two credentials data structures *match*, hashing and/or decoding the credentials data if these informations are available (i.e. the stored credentials are of `Credentials` type)
