= Holon Platform Core
:revnumber: {project-version}
:apidir: ../api/holon-core
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 4

Copyright © 2016-2017

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon Platform *Core* module represents the platform foundation, providing the definition of the overall architecture, base structures and APIs.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.core</groupId>
			<artifactId>holon-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

== What's new in version 5.1.x

* The `PropertySet` interface now supports _identifier_ properties declaration, which can be used to provide a virtual primary key to distinguish a `PropertyBox` instance from another (using the _identifier_ property values), both at Java objects level (`equals` and `hashCode`) and at persistence architecture level.

== Core API, services and components

=== Introduction

The `holon-core` artifact is the Holon platform *core* API and implementation asset, defining and providing the main platform architecture concepts and structures. All other platform artifacts derive from this one and declares it as a dependency.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-core</artifactId>
<version>{revnumber}</version>
----

include::include/core/_context.adoc[]

include::include/core/_config.adoc[]

include::include/core/_validation.adoc[]

include::include/core/_presenter.adoc[]

include::include/core/_i18n.adoc[]

include::include/core/_properties.adoc[]

include::include/core/_beans.adoc[]

include::include/core/_datastore.adoc[]

include::include/core/_tenancy.adoc[]

include::include/core/_utils.adoc[]

== HTTP and REST

The `holon-http` artifact provides base *HTTP* protocol support to the Holon platform, dealing with HTTP _messages_ and providing support for _RESTful_ web services invocation through a _client_ API.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-http</artifactId>
<version>{revnumber}</version>
----

include::include/http/_messages.adoc[]

include::include/http/_restclient.adoc[]

[[Auth]]
== Authentication and Authorization

The `holon-auth` artifact provides a complete and highly configurable *Authentication* and *Authorization* architecture, integrated with all platform modules. *HTTP* messages authentication is supported, and several APIs are provided to manage _accounts_ and their credentials, perform authentication in a *Realm* and check for *permissions*.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-auth</artifactId>
<version>{revnumber}</version>
----

include::include/auth/_realm.adoc[]

include::include/auth/_credentials.adoc[]

include::include/auth/_account.adoc[]

include::include/auth/_context.adoc[]

include::include/auth/_annotation.adoc[]

include::include/auth/_jwt.adoc[]

[[SpringIntegration]]
== Spring framework integration

The `holon-spring` artifact provides integration with the https://spring.io[Spring^] framework and auto-configuration features using https://projects.spring.io/spring-boot[Spring Boot^] for the Holon platform core module.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-spring</artifactId>
<version>{revnumber}</version>
----

include::include/spring/_context.adoc[]

include::include/spring/_tenant.adoc[]

include::include/spring/_datastore.adoc[]

include::include/spring/_restclient.adoc[]

include::include/spring/_boot.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The following logger names are available:

* `com.holonplatform.core`: the root *core* logger
** `presentation`: for logs related to values presentation
** `i18n`: for logs related to localization and internationalization
** `beans`: for logs related to bean inspection and bean properties
** `property`: for logs related to the `Property` architecture, including `PropertyBox`, property presenters and renderers
** `query`: for logs related to `Query` definition and execution
** `datastore`: for logs related to `Datastore` configuration and operation execution
* `com.holonplatform.jdbc`: for logs related to *JDBC* support classes, such as DataSource builders
* `com.holonplatform.http`: for logs related to *HTTP* support classes, such as `RestClient`
* `com.holonplatform.spring`: for logs related to https://spring.io[Spring^] integration

== System requirements

=== Java

The Holon Platform core module requires https://www.java.com[Java] *8* or higher.
