=== HTTP messages

The Holon platform provides an implementation-independent representation of the *Hypertext Transfer Protocol* request and response messages, used by other platform modules to deal with HTTP-based operations.

The HTTP request and response message representations are based on the link:{apidir}/com/holonplatform/core/messaging/Message.html[Message^] interface, which represent a generic _message_ consisting of a map of message *headers* (identified by a textual header name) and a *payload* which represents the content delivered in the message.

NOTE: For an HTTP message, the message header values are represented as a `List` of Strings, since HTTP supports multiple values for each header. The message _payload_ is represented as a `String`.

[[HttpRequest]]
==== HttpRequest

The link:{apidir}/com/holonplatform/http/HttpRequest.html[HttpRequest^] interface represents a HTTP *request* message and provides the following informations and operations:

* The HTTP *method* describing the desired action to be performed
* The fully qualified name of the client host or the last proxy that sent the request
* The request message _path_
* The request URI query parameters, if any
* The request _cookies_, if any
* An `InputStream` of the request message body (payload)

[[HttpResponse]]
==== HttpResponse

The link:{apidir}/com/holonplatform/http/HttpResponse.html[HttpResponse^] interface represents a HTTP *response* message and provides the following informations and operations:

* The HTTP _status code_ of the response, also represented with the convenience link:{apidir}/com/holonplatform/http/HttpStatus.html[HttpStatus^] enumeration
* A _builder_ to create default HttpResponse instances

==== Servlets integration

The link:{apidir}/com/holonplatform/http/servlet/ServletHttpRequest.html[ServletHttpRequest^] represents a `HttpRequest` backed by a `javax.servlet.http.HttpServletRequest` instance, and can be used as an adapter to use servlet request messages as an `HttpRequest`.

To create a `HttpRequest` from a servlet `HttpServletRequest` the `ServletHttpRequest create(HttpServletRequest request)` can be used.

This way, a servlet request can be used for example with a Holon `MessageAuthenticator`, to perform authentication operation directly using the request message. See link:core.html#MessageAuthenticator[MessageAuthenticator] section for further information. 
