[[JWT]]
=== JWT support

==== Introduction

The `holon-auth-jwt` artifact provides the support for the https://tools.ietf.org/html/rfc7519[JSON Web Token^] standard, integrating it in the Holon platform authentication and authorization architecture.

The https://github.com/jwtk/jjwt[jjwt] library is used for JWT tokens parsing and building.

JSON Web Token (*JWT*) is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. The transmitted information can be digitally signed, in order to be verified and trusted by the parties. 

When used for authentication, thanks to its very compact data representation and encoding, a JWT token can transport and provide not only the informations to perform authentication, but also the information obtained as a result of an authentication operation, such as _principal_'s details and permissions.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.core</groupId>
<artifactId>holon-auth-jwt</artifactId>
<version>{revnumber}</version>
----

==== Configuration

To enable and use JWT authentication structures, some configuration parameters must be defined and provided to the objects which perform concrete operations on the JWT tokens.

The JWT configuration properties are represented by the link:{apidir}/com/holonplatform/auth/jwt/JwtConfiguration.html[JwtConfiguration^] interface, which can be instantiated as follows:

*1.* Using the _builder_ provided by the `JwtConfiguration` interface:

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleJwt.java[tag=config,indent=0]
----

*2.* Using the configuration properties collected and represented by the link:{apidir}/com/holonplatform/auth/jwt/JwtConfigProperties.html[JwtConfigProperties^] property set, extending a default `ConfigPropertySet` and bound to the property name prefix *holon.jwt*.

The available configuration properties are listed here below:

.JWT configuration properties
|===
|Name |Type |Meaning

|_holon.jwt._ *issuer*
|String
|The JWT token issuer

|_holon.jwt._ *signature-algorithm*
|String
|JWT signature algorithm name

|_holon.jwt._ *sharedkey-base64*
|String
|JWT sign shared key (base64 encoded) for symmetric signing algorithms

|_holon.jwt._ *publickey-base64*
|String
|JWT sign public key (base64 encoded) for RSA signing algorithms

|_holon.jwt._ *publickey-file*
|String
|JWT sign public key (file name) for RSA signing algorithms

|_holon.jwt._ *privatekey-base64*
|String
|JWT sign private key (base64 encoded) for RSA signing algorithms

|_holon.jwt._ *privatekey-file*
|String
|JWT sign private key (file name) for RSA signing algorithms

|_holon.jwt._ *expire-ms*
|Integer number
|JWT token expire time in milliseconds

|_holon.jwt._ *expire-seconds*
|Integer number
|JWT token expire time in seconds

|_holon.jwt._ *expire-minutes*
|Integer number
|JWT token expire time in minutes

|_holon.jwt._ *expire-hours*
|Integer number
|JWT token expire time in hours

|_holon.jwt._ *expire-days*
|Integer number
|JWT token expire time in days

|_holon.jwt._ *include-details*
|Booelan (true/false)
|Whether to include `Authentication` details in JWT token as claims

|_holon.jwt._ *include-permissions*
|Booelan (true/false)
|Whether to include `Authentication` permissions in JWT token as claims
|===

[source, java]
.JwtConfiguration example using configuration properties
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleJwt.java[tag=config2,indent=0]
----

==== Building JWT tokens for an `Authentication`

To build JWT token the link:{apidir}/com/holonplatform/auth/jwt/JwtTokenBuilder.html[JwtTokenBuilder^] class is available, providing static methods to create a *JWT token* from an `Authentication` object, optionally using a `JwtConfiguration` class to provide token configuration attributes.

If enabled, the *permissions* and *parameters* of the `Authentication` will be written in the JWT token with the following behaviour:

* The `Authentication` *permissions* will be written only for the permissions which provides a `String` representation through the `Permission.getPermission()` method. The serializable permissions are written as String array and associated to the _claim_ name which corresponds to the constant `AuthenticationClaims.CLAIM_NAME_PERMISSIONS` value;
* Each `Authentication` *parameter* will be written by using the parameter name as _claim_ name and the parameter value as _claim_ value.

[source, java]
.JWT token building example using JwtConfiguration
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleJwt.java[tag=build,indent=0]
----
<1> Build a `JwtConfiguration` instance using the `jwt.properties` file
<2> Build an example `Authentication`
<3> Build a JWT *token* by using given configuration and authentication, using a random id as token id

==== Performing authentication using JWT tokens

The link:{apidir}/com/holonplatform/auth/jwt/JwtAuthenticator.html[JwtAuthenticator^] interface is provided as `Authenticator` to handle JWT token based authentication, using a `JwtConfiguration` to obtain JWT token configuration attributes.

The authentication request information are provided by using a `BearerAuthenticationToken`, where the *Bearer* value represents the complete JWT token serialization.

From an `HTTPMessage` point of view, the authentication token is obtained from an `Authorization` header using the `Bearer` scheme.

To obtain a `JwtAuthenticator`, the provided _builder_ can be used. The authenticator, just like any other `Authenticator`, must be registered in a `Realm` to enable JWT token based authentication.

The `JwtAuthenticator` supports:

* An optional set of allowed *JWT issuers*: If one ore more allowed issuer is setted, JWT Issuer _claim_ (`iss`) will be required and checked during token authentication: if token issuer doesn't match one of the given issuers, authentication will fail;
* Optional *required claims*: If one or more required _claim_ is configured, the specified _claim_ must exist in JWT token, otherwise authentication will fail.

[source, java]
.JWT token building example using JwtConfiguration
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleJwt.java[tag=authenticator,indent=0]
----
