[[Realm]]
=== Realm

The link:{apidir}/com/holonplatform/auth/Realm.html[Realm^] API represents a security abstraction providing operations for _principals_ *authentication* and *authorization*.

The `Realm` API is the main entry point to deal with the Holon Platform authentication and authorization architecture: it holds the configuration of the authentication and authorization context and provides operations to perform _principals_ authentication and authorization controls.

The `Realm` *authentication strategy* is defined using a set of _authenticators_, represented by the link:{apidir}/com/holonplatform/auth/Authenticator.html[Authenticator^] interface, each bound to a specific link:{apidir}/com/holonplatform/auth/AuthenticationToken.html[AuthenticationToken^], which represents the principal's credentials.

In a mirrored way, the `Realm` *authorization strategy* is defined using a set of _authorizers_, represented by the link:{apidir}/com/holonplatform/auth/Authorizer.html[Authorizer^] interface, each bound to a specific link:{apidir}/com/holonplatform/auth/Permission.html[Permission^] type, and used by the `Realm` API to perform authorization controls against the principal's granted permissions.

The _authenticators_ and _authorizers_ bound to a specific `Realm` instance define the authentication and authorization strategy of such `Realm`, so they are registered at `Realm` configuration time.

The `Realm` API provides a _fluent_ builder to build and configure a `Realm` instance, with _authenticators_ and _authorizers_ registration methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=builder,indent=0]
----
<1> Obtain a `Realm` builder
<2> Register an `Authenticator`
<3> Register another `Authenticator`
<4> Register an `Authorizer`
<5> Register another `Authorizer`

The <<Authenticator>> and <<Authorizer>> sections describe these API definitions in detail.

==== Realm name

A `Realm` instance can be identified by a *name*, which can be used to identify a specific `Realm` instance when more than one is available.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=name,indent=0]
----
<1> Set the `Realm` name using the default builder
<2> Get the `Realm` name, if available

[[RealmAuthentication]]
==== Ream authentication

To perform an _authentication_, the `Realm` API provides the `authenticate(AuthenticationToken authenticationToken)` method.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=authenticator1,indent=0]
----
<1> Perform an authentication request using the `MyAuthenticationToken` authentication token type

The `Realm` API itself does not implement any authentication model or strategy, but delegates the specific authentication strategy to one or more concrete <<Authenticator>>, relying on the `AuthenticationToken` type in order to discern which `Authenticator` has to be used to handle the authentication process.

The authentication flow is structured as follows:

. A concrete `AuthenticationToken`, which represents the authentication request (for example, the  _principal_'s credentials), is provided to the `authenticate` method;
. The Realm checks if a suitable `Authenticator` is registered, i.e. an `Authenticator` which can handle the given `AuthenticationToken` type. If not, an `UnsupportedTokenException` is thrown;
. The `authenticate(AuthenticationToken authenticationToken)` method is called on the specific `Authenticator` API, performing the concrete authentication operation.
. If the authentication operation is successful, the authenticated principal is returned using `Authentication` representation.
. Otherwise, an `AuthenticationException` type is thrown. The concrete type of the exception gives more detailed informations on what went wrong.

Each `Authenticator` declares the <<AuthenticationToken>> type to which is bound through the `getTokenType()` method. When a new `Authenticator` is registered, the `Realm` instance will support the `AuthenticationToken` type which is bound to the registered `Authenticator`, and such `Authenticator` will be used to perform the authentication operation when a matching `AuthenticationToken` type is provided.

TIP: See the <<Authenticator>> section to learn how an `Authenticator` can be registered in a `Realm` instance.

To check if a `Realm` instance supports a specific `AuthenticationToken` type, the `supportsToken` API method can be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=authenticator2,indent=0]
----
<1> Checks whether given `Realm` supports the `MyAuthenticationToken` authentication token type

See the next section for details about authenticators, authentication tokens and the authenticated principal representation.

[[AuthenticationToken]]
==== AuthenticationToken

The link:{apidir}/com/holonplatform/auth/AuthenticationToken.html[AuthenticationToken^] interface represents an authentication request, and provides the following methods:

* `getPrincipal()`: the *principal* this authentication token refers to, i.e. the account identity submitted during the authentication process. The return type is a generic `Object`, since each authentication model could provide the _principal_ information in a different way.
* `getCredentials()`: the *credentials* submitted during the authentication process that verifies the submitted _principal_ account identity. The return type is a generic `Object`, since each authentication model could represent the _principal_ credentials in a different way.

Each `AuthenticationToken` sub-type is bound to an <<Authenticator>>, which is able to interpret the _principal_ and _credentials_ representations and to perform the actual authentication process using the information provided through the `AuthenticationToken` instance.

Some builtin `AuthenticationToken` representations are provided by the core Holon Platform module:

[[AccountCredentialsToken]]
===== Account credentials authentication token

The _account credentials_ token represents generic account authentication information, where an _account_ is identified by a String type *id* (similar to a _username_) and a String type *secret* (similar to a _password_).

This token returns the account *id* from the `getPrincipal()` method, and the account *secret* from the `getCredentials()` method.

An account credentials token can be created by using the static `accountCredentials(...)` method of the `AuthenticationToken` interface:

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=accounttoken,indent=0]
----
<1> Create an _account credentials_ authentication token type using `username` as account id (the principal's name) and `password` as account secret (the account credentials)

[[BearerAuthenticationToken]]
===== Bearer authentication token

The _bearer_ token represents a String type information which identifies (or it is bound to) a _principal_ and can be used to perform the authentication or grant the access to a resource, checking the token validity. This kind of token is used, for example, in _OAuth_ or _JWT_ authentication and authorization models.

This token returns `null` from the `getPrincipal()` method, and the *bearer token* from the `getCredentials()` method.

A bearer token can be created using the static `bearer(...)` method of the `AuthenticationToken` interface:

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=bearertoken,indent=0]
----
<1> Create a _bearer_ authentication token type, providing the token value

[[Authenticator]]
==== Authenticator

As stated in the <<RealmAuthentication>> flow description, the `Realm` API relies on the registered `Authenticator` instances to perform the actual authentication process, according to the provided `AuthenticationToken` type.

The link:{apidir}/com/holonplatform/auth/Authenticator.html[Authenticator^] API represents a concrete authentication strategy, using a specific `AuthenticationToken` type to represent the authentication request. The `AuthenticationToken` type to which an `Authenticator` is bound is provided by the `getTokenType()` method.

The `authenticate(AuthenticationToken authenticationToken)` method of the link:{apidir}/com/holonplatform/auth/Authenticator.html[Authenticator^] API is used to perform the actual authentication operation, checking the principal's credentials provided through the `AuthenticationToken` instance and returning an <<Authentication>> representation of the authenticated principal if the process was successful.

When an authentication request is not successful, an `AuthenticationException` type is thrown. The concrete type of the exception gives more detailed informations on what went wrong. See <<AuthenticationExceptions>> for a list of the authentication exceptions available by default.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=authenticator3,indent=0]
----
<1> Create an `Authenticator` bound to the `MyAuthenticationToken` authentication token type
<2> Perform an authentication request on the `Authenticator`, obtaining the authenticated principal representation if successful.
<3> If the authentication request is not successful, an `AuthenticationException` type is thrown

TIP: See the <<Authentication>> section for information about the authenticated principal representation

===== `Authenticator` registration

An `Authenticator` can be registered in a `Realm` instance in two ways:

* Using the `Realm` API _builder_.
* Using the `addAuthenticator` method of the `Realm` API.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=builder2,indent=0]
----
<1> Add a Realm `Authenticator` using the _builder_ API
<2> Add a Realm `Authenticator` using the `Realm` API method

===== Builtin authenticators

* See the <<Account>> section to learn about the builtin _account credentials_ type authenticator.
* See the <<JWT>> section learn about the builtin _JSON Web Token_ type authenticator.

[[AuthenticationExceptions]]
==== Authentication exceptions

Below a list of the default authentication exceptions.

|===
|Class |Meaning

|`InvalidCredentialsException`
|Provided credentials are not valid or do not match the stored credentials

|`ExpiredCredentialsException`
|Provided credentials are expired

|`UnexpectedCredentialsException`
|An unexpected internal error occurred during credentials match

|`DisabledAccountException`
|Account is disabled

|`LockedAccountException`
|Account is locked

|`UnknownAccountException`
|Unknown account

|`InvalidTokenException`
|The authentication token is not valid

|`UnsupportedTokenException`
|Unsupported authentication token type

|`UnsupportedMessageException`
|Unsupported authentication message

|`UnexpectedAuthenticationException`
|Generic authentication process failure
|===

[[Authentication]]
===== Authentication

The result of an `Authenticator` successful authentication request is represented by the link:{apidir}/com/holonplatform/auth/Authentication.html[Authentication^] API.

An `Authentication` object represents the authenticated _principal_, and extends the default `java.security.Principal` interface, inheriting the `getName()` method to obtain the name which identifies the _principal_.

In addition, the `Authentication` interface holds and provides the following informations:

* An optional set of <<Permission>> granted to the authenticated principal.
* A `isRoot()` flag, to mark the authenticated _principal_ as a _root_ principal, i.e. for which the permission checking is always skipped, assuming that any permission is granted to this _principal_.
* The optional _scheme_ information, to identify the authentication scheme with which the _principal_ was authenticated. See <<MessageAuthenticator>> for details about authentication schemes.
* It extends the Holon Platform link:{apidir}/com/holonplatform/core/ParameterSet.html[ParameterSet^] API, which represents a set of custom name-value attributes and can be used to provide additional, custom information related to the authenticated _principal_.

An `Authentication` can be extended to provide more application-specific informations about the authenticated _principal_, if the parameter set support is not enough or too much generic.

The `Authentication` API provides a _builder_ to create new `Authentication` instances.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=authentication,indent=0]
----
<1> Obtain an `Authentication` _builder_ and set `userId` as principal name
<2> Add a `VIEW` String type granted permission (using the _role_ name convention)
<3> Add a custom `MyPermission` type granted permission
<4> Add `name` named parameter
<5> Add `surname` named parameter
<6> Set `myscheme` as authentication scheme

[[AuthenticationListeners]]
==== Authentication listeners

The link:{apidir}/com/holonplatform/auth/Authentication.AuthenticationListener.html[AuthenticationListener^] interface can be used to be notified when a successfull authentication is performed. The authenticated principal, represented as an <<Authentication>> instance, is provided to the listener method.

The link:{apidir}/com/holonplatform/auth/Authentication.AuthenticationNotifier.html[AuthenticationNotifier^] API allows to add and remove an `AuthenticationListener`. The `AuthenticationNotifier` is implemented by the `Realm` API, so an `AuthenticationListener` can be registered in a `Realm` instance to be notified when a successfull authentication request is performed.

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=listener,indent=0]
----
<1> Add an `AuthenticationListener` to given `Realm` instance

[[MessageAuthenticator]]
==== MessageAuthenticator

The link:{apidir}/com/holonplatform/auth/Authenticator.MessageAuthenticator.html[MessageAuthenticator^] interface represents an intermediate _authenticator_ API, specialized for `Message` based authentication.

The authentication request is provided using a `Message`, for example a HTTP request message. Such message is translated into an `AuthenticationToken` using an link:{apidir}/com/holonplatform/auth/AuthenticationToken.AuthenticationTokenResolver.html[AuthenticationTokenResolver^] registered in the `MessageAuthenticator`. From now on, the authentication process proceed as usual, using the obtained `AuthenticationToken` and a suitable <<Authenticator>> to accomplish the actual authentication operation in `Realm`.

Unlike the standard `Authenticator`, the `MessageAuthenticator` provides a specialized method which accepts a `Message` as authentication request representation:

[source, java]
----
authenticate(Message<?, ?> message, String... schemes)
----

===== AuthenticationTokenResolver

The link:{apidir}/com/holonplatform/auth/AuthenticationToken.AuthenticationTokenResolver.html[AuthenticationTokenResolver^] is responsible for the authentication `Message` handling, and must provide a standard `AuthenticationToken` which represents the authentication message to be used to perform actual authentication in `Realm`.

An `AuthenticationTokenResolver` can optionally declare the authentication _scheme_ it is bound to, in order to discern different messages authentication information within a set of messages of the same type, and select the most suitable `AuthenticationTokenResolver` relying on the authentication scheme name.

For example, within the set of the HTTP request messages type, different authentication schemes, such as _Basic_ or _Bearer_, can be bound to a different `AuthenticationTokenResolver`, producing different `AuthenticationToken` s.

For link:http.html#HttpRequest[HttpRequest] message types, two builtin `AuthenticationTokenResolver` are provided:

* For the *Basic* HTTP authentication scheme, using the `Authorization` header, producing a <<AccountCredentialsToken>>:

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=basic,indent=0]
----

* For the *Bearer* HTTP authentication scheme, using the `Authorization` header, producing a <<BearerAuthenticationToken>>:

[source, java]
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=bearer,indent=0]
----

An `AuthenticationTokenResolver` must be registered in `Realm` using the `addAuthenticationTokenResolver(...)` method.

[source, java]
.AuthenticationTokenResolver registration and use
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=resolver,indent=0]
----
<1> Register a HTTP *Basic* message resolver in Realm
<2> Perform authentication using a `HTTPRequest` mesage

[[Authorizer]]
==== Authorizer

The link:{apidir}/com/holonplatform/auth/Authorizer.html[Authorizer^] interface is responsible for authorization control, checking if one or more _permissions_ are granted to a _principal_.

An `Authorizer` uses the <<Authentication>> representation to obtain the *permissions* granted to an authenticated _principal_, and provides several `isPermitted...` methods to perform permission control.

[[Permission]]
===== Permission

A *permission* is the representation of the access to a resource and can be expressed int two ways:

* As a `String`: this can be compared to a *Role* name.
* Using the link:{apidir}/com/holonplatform/auth/Permission.html[Permission^] interface. This interface can be extended and implemented in different ways to represent more complex permissions than a simple role name. The default `Authorizer` relies on the `equals()` and `hashCode()` implementation to perform `Permission` comparison.

To handle a custom `Permission` type, when the `equals()`/`hashCode()` comparison logic is not suitable or applicable, a custom `Authorizer` can be registered to the `Realm`, providing the right permission checking strategy for the custom `Permission` type. See below for further details.

TIP: A `Permission` object which uses a simple String name can be created using the `Permission.create(String permission)` static method.

===== Authorization checking

Each `Authorizer` can be bound to a specific `Permission` type, to create specialized authorizers which handle a specific permission type.

To enable *authorization checking* for a `Realm`, the available authorizers must be registered in realm using the `addAuthorizer(...)` method.

The platform provides a *default* `Authorizer` which can be obtained using the `Authorizer.create()` static method. The default authorizer is bound to a generic `Permission` type and permission checking is performed by comparing  the`Authentication` granted permissions with the permissions to be checked, using the `Permission.equals(...)` method to compare a single permission to another.

The default `Authorizer` supports the `Authentication.isRoot()` state, always granting permissions to *root* authentications.

[source, java]
.Authorization example
----
include::{examplesdir}/com/holonplatform/core/examples/ExampleRealm.java[tag=permissions,indent=0]
----
